### PR TITLE
Backport Beam PR-828: Set Gcs upload buffer size to 1M in DataflowRunner streaming mode

### PR DESCRIPTION
**Pull request by peihe**

### CODE REVIEW

**Comment by peihe** [comment]
R: @lukecwik

**Comment by lukecwik** [comment]
LGTM

**Comment by lukecwik** [comment]
checkstyle failure:
DataflowPipelineRunner.java:136:8: Unused import: com.google.cloud.hadoop.util.AbstractGoogleAsyncWriteChannel.

**Comment by peihe** [comment]
fixed unused import

**Pull request merged**
