### PR TITLE
pom.xml: upgrade to version 1.22.0 of the Google API client libs

### PR DESCRIPTION
**Pull request by dhalperi**
Backport of apache/incubator-beam#303

I have not inspected the backport auto-merge closely but I will.

R: @lukecwik

### CODE REVIEW

**Comment by lukecwik** [comment]
LGTM

**Comment by lukecwik** [comment]
You also re-ordered the order the gcsio dependency

**Comment by lukecwik** [comment]
And made sure the http client lib got updated from 1.20 to 1.22

**Comment by dhalperi** [comment]
HTTP Client Libs: ported.
gcsio: already ordered correctly here.

**Comment by lukecwik** [comment]
LGTM

**Pull request merged**
