### PR TITLE
Fix undefined property bug

### LINKED ISSUE #633: Undefined parameter in pom.xml for StarterPipeline 2.4 Dataflow archetype
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/3043

```xml
<maven-exec-plugin.version>@maven-exec-plugin.version@</maven-exec-plugin.version>
```

Should be `exec-maven-plugin` (or `exec-maven-plugin` in other places should be `maven-exec-plugin`). Let me create a PR.

### PR DESCRIPTION
**Pull request by chanseokoh**
Fixes #633.

### CODE REVIEW

**Comment by chanseokoh** [comment]
I'll fix the test.

**Comment by chanseokoh** [comment]
ping

**Comment by huygaa11** [comment]
@lukecwik yes, I can do that in a consequent PR.

**Comment by huygaa11** [comment]
@chanseokoh If you would like to contribute to Beam, feel free to send a PR to beam repo. Let me know if you are interested :).

Here is the file in Beam:
https://github.com/apache/beam/blob/master/sdks/java/maven-archetypes/starter/src/main/resources/archetype-resources/pom.xml

**Comment by chanseokoh** [comment]
@huygaa11 sure, let me do that.

**Comment by chanseokoh** [comment]
@huygaa11 there's some gradle stuff that I don't understand, so I'll just create a new issue and leave it to you.

**Comment by huygaa11** [comment]
No worries. Thanks for looking into it.

**Comment by chanseokoh** [comment]
On the Beam repo, I find

`build_rules.gradle:    maven_exec_plugin: "maven-plugins:maven-exec-plugin:1.6.0",`

`sdks/java/maven-archetypes/examples/build.gradle:    'maven-exec-plugin.version': dependencies.create(project.library.maven.maven_exec_plugin).getVersion(),`

I wonder if they should be `exec-maven-plugin` in both cases.

Do note that you'll find a lot of instances of `maven-exec-plugin` with `git grep maven-exec-plugin`.

**Comment by lukecwik** [comment]
Sure, swapping so the property name better aligns with the name of the plugin makes sense.

**Pull request merged**
