### PR TITLE
[BEAM-222] Backport BEAM pull/235

### PR DESCRIPTION
**Pull request by mshields822**

### CODE REVIEW

**Comment by mshields822** [comment]
R: @davorbonaci 

Note this will break sdk.runners.worker. WorkerCustomSourcesTest

**Comment by mshields822** [comment]
Revised to also track BEAM pull/248

**Comment by davorbonaci** [comment]
LGTM, from my perspective.

However, @dhalperi has merged Beam changes -- he should take a final look and merge.

**Comment by dhalperi** [comment]
It looks like this is a backport of:

* https://github.com/apache/incubator-beam/pull/132
* https://github.com/apache/incubator-beam/pull/235
* https://github.com/apache/incubator-beam/pull/248

Is that right, Mark?

It looks like some of the changes in 132 are missing. Intentional?

**Comment by mshields822** [comment]
I kept the new sharding option in TestCountingSource for simplicity of
backporting. I did not backport the BoundedReadFromUnboundedSourceTest
changes.

**Pull request merged**
