### PR TITLE
Salesforce source and sink code

### PR DESCRIPTION
**Pull request by springml**
We've been working with Eric Anderson at Google on Salesforce connectors.  Here's our first version of the prototype code that we demo'd to Eric.

### CODE REVIEW

**Comment by springml** [comment]
We signed the CLA as a corporation.  Our company is springML.

**Comment by springml** [comment]
We received notification that the CLA has been filed.  I am hoping someone will respond to this pull request?  Please do let me know if there's anything I need to do.

**Comment by springml** [comment]
CLA signed

**Comment by springml** [comment]
CLA signed

**Comment by springml** [comment]
Confirming that I did the commits.

**Comment by springml** [comment]
Confirming that I did the commits.

**Comment by davorbonaci** [comment]
Hi there,
We are looking into these and will get back to you shortly with our comments, if any.

Thanks for your contribution!

**Comment by Aki11es** [comment]
Cool!

**Comment by davorbonaci** [comment]
Note: a fork seems to have been pushed to https://github.com/springml/dataflow-salesforce repository.

**Comment by davorbonaci** [comment]
CLA confirmed.

**Comment by dhalperi** [comment]
@springml I apologize profusely for the ludicrous delay here. I'm in the process of finding and picking up the balls we've dropped.

I see you are now serving the code this connector in the repo https://github.com/springml/dataflow-salesforce linked above. Do you still wish it to be contributed into this GoogleCloudPlatform repository?

**Comment by springml** [comment]
Hello Daniel,

Yes we would like to contribute to GCP repo. Please let me know next steps.

Thank you.

-Girish

**Comment by springml** [comment]
Moving to springml's github repo in light of dataflow becoming an apache project - will follow and contribute to the new project.

**Comment by davorbonaci** [comment]
Thanks guys!

**Pull request closed without merging**
