### PR TITLE
Fix InProcessPipelineRunner to handle a null subscription

### PR DESCRIPTION
**Pull request by sammcveety**
R: @tgroh

### CODE REVIEW

**Comment by sammcveety** [comment]
For verifying the subscription, is the least-bad way I can see is to make an additional factory method that includes a verifyCreateSubscription toggle.  Anything nicer than that?

**Comment by dhalperi** [comment]
better link: https://github.com/apache/beam/pull/1817

**Comment by sammcveety** [comment]
I think this is a different issue (not present in Beam), made obsolete by
the new structure of the function in question.

**Comment by tgroh** [comment]
I don't think there's anything nicer than that, but I'm not particularly bothered (given that it's a `PubsubTestClientFactory`)

**Comment by sammcveety** [comment]
Done, please take another look.

**Pull request merged**
