### PR TITLE
DatastoreIO v1beta3 to v1 version

### PR DESCRIPTION
**Pull request by vikkyrk**
- Backport from https://github.com/apache/incubator-beam/pull/858

### CODE REVIEW

**Comment by vikkyrk** [comment]
R: @dhalperi

**Comment by lnealan** [comment]
Any chance this can be released soon? When running dataflowSdk together the dataflow API included in gcloud all my dataflow calls fail with protobuf errors. I tested with 1.7.0-SNAPSHOT which includes this change and had no issues. I wanted to make you aware and see if you could accelerate the release of 1.7.0 or a 1.6.x with this changeset.

**Comment by vikkyrk** [comment]
@lnealan 1.7 is going to be released soon, so you will have to wait for it, no plans to add it to 1.6.x.

**Comment by mpavlov** [comment]
Does 1.6.x use dataflow api v1beta2? That api is scheduled for turndown in 2 weeks: https://cloud.google.com/datastore/docs/apis#cloud-datastore-api-v1beta2-deprecated

**Comment by vikkyrk** [comment]
@mpavlov yes it is uses v1beta2. However @dhalperi is working on getting the 1.7.x release out, which uses the v1 version of Cloud Datastore. Once that is released, users will have to migrate to 1.7.x.

**Comment by vikkyrk** [comment]
@mpavlov @lnealan [1.7.0](https://cloud.google.com/dataflow/release-notes/release-notes-java#170) is released with Datastore v1 version.

**Comment by mpavlov** [comment]
thanks @vikkyrk!

**Pull request merged**
