### PR TITLE
Add Missing RunWith to WriteWithShardingFactoryTest

### PR DESCRIPTION
**Pull request by tgroh**

### CODE REVIEW

**Comment by tgroh** [comment]
R: @dhalperi

**Comment by bjchambers** [comment]
LGTM. Can merge when travis is green (ping me if I forget).

**Comment by dhalperi** [comment]
Travis seems stuck. Build 1137 finished 3 hours ago, but build 1138 hasn't started yet.

I cloned this branch locally and ran all the tests, and it passed. I'll merge now to unblock downstream processed.

**Comment by dhalperi** [comment]
1137: https://travis-ci.org/GoogleCloudPlatform/DataflowJavaSDK/builds/157149207

1138: https://travis-ci.org/GoogleCloudPlatform/DataflowJavaSDK/builds/157196243

**Pull request merged**
