### PR TITLE
Update dataflow version in pom.xml to maven latest

### PR DESCRIPTION
**Pull request by joshualitt**

### CODE REVIEW

**Comment by joshualitt** [comment]
I signed it!

**Comment by dhalperi** [comment]
Looks like this change has not yet been made in Apache Beam. Please submit there first, then we can backport to DataflowJavaSDK.

**Comment by dhalperi** [comment]
This is a backport of https://github.com/apache/incubator-beam/pull/548

**Comment by dhalperi** [comment]
CLAs are good -- @joshualitt works for google.

**Pull request merged**
