### PR TITLE
Backport recent DisplayData changes

### PR DESCRIPTION
**Pull request by swegner**

### CODE REVIEW

**Comment by swegner** [comment]
R: @bjchambers 

Nothing interesting here, pure backport.

**Comment by dhalperi** [comment]
R: @bjchambers

**Comment by bjchambers** [comment]
I see a build/test failure:

Failed tests: 
  BigQueryIOTest.testBatchSinkPrimitiveDisplayData:595->testSinkPrimitiveDisplayData:614 BigQueryIO.Write should include the table spec in its primitive display data
Expected: a collection containing display data with item: with key is "tableSpec"
     but: found 0 non-matching item(s):

**Comment by swegner** [comment]
> I see a build/test failure:

Looks like there had been some BigQueryIO work that isn't backported which broke the tests for primitive display data. I've manually updated the code.

This now has all DisplayData backports in it. PTAL @bjchambers

**Pull request merged**
