### PR TITLE
Use encoded Elements in the DirectPipelineRunner

### LINKED ISSUE #434: DataflowAssert serde cycle on actual values
Afaiu `CheckRelationAgainstExpected` from [DataflowAssert](https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/master/sdk/src/main/java/com/google/cloud/dataflow/sdk/testing/DataflowAssert.java#L1022), it does serde cycle on expected values, while actual values coming from PCollection would not go through the same cycle. This may lead to inconsistency, for example in case of TableRow/TableRowJsonCoder/Jackson:
   
  * http://stackoverflow.com/questions/33622227/dataflow-mixing-integer-long-types
  * http://stackoverflow.com/questions/7316689/forcing-jackson-to-deserialize-to-specific-primitive-type

What do you think about enforcing serde cycle on PCollection before matching with `expected` values?

This issue came up in spotify/scio#252

### PR DESCRIPTION
**Pull request by tgroh**
This should fix #434

### CODE REVIEW

**Comment by tgroh** [comment]
R: @kennknowles

**Comment by kennknowles** [comment]
Travis failure looks real but unrelated to this change. I just looked at the last error; maybe something went sideways in the log somewhere?

**Comment by tgroh** [comment]
Yeah, it looks like `BoundedReadFromUnboundedSourceTest` exploded (`#testTimeBound` in at least one of the cases)

**Comment by tgroh** [comment]
@kennknowles 

reducing the read time in `BoundedReadFromUnboundedSourceTest` continues to demonstrate that it applies a limited read, but reduces the pressure on Travis. PTAL.

**Pull request merged**
