### PR TITLE
Fixed documentation

### PR DESCRIPTION
**Pull request by anilmuppalla**

### CODE REVIEW

**Comment by dhalperi** [comment]
Valid corporate CLA.

**Comment by dhalperi** [comment]
Thanks for this nice fixup.

**Comment by dhalperi** [comment]
Btw, would you also send a PR to Apache Beam, which is the basis of Dataflow 2? Looks like we have the same bug there: https://github.com/apache/beam/blob/master/sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/windowing/AfterWatermark.java

**Comment by anilmuppalla** [comment]
done. https://github.com/apache/beam/pull/2444

**Pull request merged**
