### PR TITLE
Add option to disable cloning DoFn in DoFnTester

### PR DESCRIPTION
**Pull request by vikkyrk**
- Porting this from https://github.com/apache/incubator-beam/pull/697

### CODE REVIEW

**Comment by vikkyrk** [comment]
R: @dhalperi @kennknowles

**Comment by kennknowles** [comment]
LGTM - even though a user's `DoFn` must be serializable, this is handy for testing with auxiliary bits that are not. Waiting for test results, which are looking green but two more to go.

**Comment by vikkyrk** [comment]
@kennknowles tests look good. Will you merge it or waiting for Dan to take a look?

**Comment by vikkyrk** [comment]
Thanks

**Pull request merged**
