### PR TITLE
Backport PR from Beam: "define executingProject, and use it for creating BigQuery jobs"

### PR DESCRIPTION
**Pull request by peihe**

### CODE REVIEW

**Comment by peihe** [comment]
R: @dhalperi 

Differences comes from: replacing try catch with toJsonString()

**Comment by dhalperi** [comment]
What Beam PR is this a backport of? Please always link them via github links

**Comment by dhalperi** [comment]
Backport of https://github.com/apache/incubator-beam/pull/369

**Comment by dhalperi** [comment]
Please add a unit test that would have caught this bug.

**Comment by peihe** [comment]
added unit test.

**Pull request merged**
